name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  push-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run metrics scripts
        run: |
          python metrics/count_tokens.py || echo 'count_tokens missing'
          python metrics/complexity.py || echo 'complexity missing'
          python metrics/pr_latency.py || echo 'pr_latency missing'
      - name: Push metrics
        env:
          METRICS_ENDPOINT: ${{ secrets.METRICS_ENDPOINT }}
        run: |
          echo "Pushing metrics to $METRICS_ENDPOINT"
